import { useState } from 'react'
import Head from 'next/head'
import quotes from '../assets/quotes.json'
const colorArr = ["#ffb3ba", "#ffdfba", "#ffffba", "#baffc9", "#bae1ff"]


export default function Home() {
  const [quote, setQuote] = useState(quotes[0])
  const [bgColor, setBgColor] = useState(colorArr[0])

  const randomQuote = () => {
    const randomNum = Math.floor(Math.random() * quotes.length)
    const randomColor = Math.floor(Math.random() * colorArr.length)

    if (quotes[randomNum] === quote || colorArr[randomColor] === bgColor) {
      randomQuote()
    } else {
      setQuote(quotes[randomNum])
      setBgColor(colorArr[randomColor])
    }
  }
  return (
    <>
      <Head>
        <title>Colorful Quote Machine</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet' />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="background-cover">
        <div id="quote-box" style={{backgroundColor: bgColor, boxShadow: `0 0 10px ${bgColor}`}}>
          <p id="text">&quot;{quote.quote}&quot;</p>
          <div id="author">-{quote.author}</div>
          <div className="buttons-wrapper">
            <a href="https://twitter.com/intent/tweet" id="tweet-quote" target="_blank" rel="noreferrer">
              <button>Tweet Quote</button>
            </a>
            <button onClick={randomQuote} id="new-quote">
              New Quote
            </button>
          </div>
        </div>
      </main>
    </>
  )
}
